#!/bin/bash
REPO_NAME=opencode
DEFAULT_BRANCH=master
cd ${REPO_NAME}
git checkout ${DEFAULT_BRANCH}
if ! git remote | grep -q "^${REPO_NAME}\$"; then
	git remote add ${REPO_NAME}  https://github.com/anomalyco/opencode.git
fi
git pull ${REPO_NAME} dev && git push origin ${DEFAULT_BRANCH}
git fetch ${REPO_NAME} --tags dev -f && git push origin ${DEFAULT_BRANCH} --tags -f
